# -*- coding: utf-8 -*-
"""
Created on Fri Jul 14 20:18:15 2023

@author: HP
"""
import pandas as pd
df1=pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\Fathima\importing_files\friend_names.csv",sep=",")
print(df1)
print(df1.head())
print(df1.tail())
print(df1.info())
print(df1.columns)
print(df1.dtypes)
df1.index

df2=pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\Fathima\importing_files\familymember_names.txt",sep="*")
print(df2)
print(df2.head())
print(df2.tail())
print(df2.info())
print(df2.columns)
print(df2.dtypes)
print(df2.index)

df3=pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\Fathima\importing_files\VegFood_names.txt",sep="|")
print(df3)
print(df3.head())
print(df3.tail())
print(df3.info())
print(df3.columns)
print(df3.dtypes)
print(df3.index)


df4=pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\Fathima\importing_files\nonveg items.txt",sep="|")
print(df4)
print(df4.head())
print(df4.tail())
print(df4.info())
print(df4.columns)
print(df4.dtypes)
print(df4.index)

df5=pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\Fathima\importing_files\month name_season.txt",sep="&")
print(df5)
print(df5.head())
print(df5.tail())
print(df5.info())
print(df5.columns)
print(df5.dtypes)
print(df5.index)

df6=pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\Fathima\importing_files\colour_names.txt",sep="^")
print(df6)
print(df6.head())
print(df6.tail())
print(df6.info())
print(df6.columns)
print(df6.dtypes)
print(df6.index)

df7=pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\Fathima\importing_files\friends_names.csv")
print(df7)
print(df7.head())
print(df7.tail())
print(df7.info())
print(df7.columns)
print(df7.dtypes)
print(df7.index)

df8=pd.read_excel(r"C:\Users\HP\OneDrive\Desktop\Fathima\importing_files\family_members.xlsx")
print(df8)
print(df8.head())
print(df8.tail())
print(df8.info())
print(df8.columns)
print(df8.dtypes)
print(df8.index)

df9=pd.read_excel(r"C:\Users\HP\OneDrive\Desktop\Fathima\importing_files\vegfood_items.xlsx")
print(df9)
print(df9.head())
print(df9.tail())
print(df9.info())
print(df9.columns)
print(df9.dtypes)
print(df9.index)

df10=pd.read_excel(r"C:\Users\HP\OneDrive\Desktop\Fathima\importing_files\nonveg_items.xlsx")
print(df10)
print(df10.head())
print(df10.tail())
print(df10.info())
print(df10.columns)
print(df10.dtypes)
print(df10.index)

df11=pd.read_excel(r"C:\Users\HP\OneDrive\Desktop\Fathima\importing_files\months_with_season.xlsx")
print(df11)
print(df11.head())
print(df11.tail())
print(df11.info())
print(df11.columns)
print(df11.dtypes)
print(df11.index)

df12=pd.read_excel(r"C:\Users\HP\OneDrive\Desktop\Fathima\importing_files\colours_names.xlsx",sheet_name='colours')
print(df12)
print(df12.head())
print(df12.tail())
print(df12.info())
print(df12.columns)
print(df12.dtypes)
print(df12.index)
